sudo: required
dist: trusty

services:
  - docker

language: go

go:
  - 1.7
  - 1.8
  - tip
os:
  - linux

matrix:
  allow_failures:
    - go: tip

script:
  - make install -C ./backend
  - make test -C ./backend
