language: go
go:
  - 1.6.3
  - 1.7.3
os:
  - linux

sudo: false
dist: trusty

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres -f postgres/schema.sql

script:
  - go get -t -v ./backend/...
  - go test ./backend/...
