version: '2'
services:
  frontend:
    restart: always
    build: ./frontend
    volumes:
      - .:/frontend

  backend:
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - .:/backend
    command: ./start-backend.sh

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - frontend
    links:
      - frontend:frontend
      - backend:backend

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb
