secret_key: "just a random secret string"
auth_token_validity_period: 15
refresh_token_validity_period: 1440
random_password_length: 128

database:
  username: "postgres"
  password: "postgres"
  host: "database"
  port: "5432"

redis:
  password: ""
  host: "cache"
  port: "6379"
  db: 0
  cache_expiration_time: 1m

authorization_google:
  client_id: "248788072320-cgap8rml3940qugk1u1i1c77onukabnn.apps.googleusercontent.com"
  client_secret: "V4lFJ6QWLP117cNN9Y2O3wGj"
  callback_uri: "http://frontend.show/login/google/callback"
  project_id: "chirp-mimuw"
  auth_url: "https://accounts.google.com/o/oauth2/auth"
  token_url: "https://accounts.google.com/o/oauth2/token"

elasticsearch:
  username: "elastic"
  password: "changeme"
  host: "elasticsearch"
  port: "9200"
