secret_key: "super random string for tests"
auth_token_validity_period: 15
refresh_token_validity_period: 1440

database:
  username: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5433"

redis:
  password: ""
  host: "localhost"
  port: "6379"
  db: 0
  cache_expiration_time: 0s
