version: '2'
services:
  backend:
    restart: always
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    volumes:
      - ../backend:/backend
    links:
      - postgres:database
      - redis:cache
      - elasticsearch:elasticsearch
    command: /go/bin/backend

  postgres:
    extends:
      file: core.yml
      service: postgres

  redis:
    extends:
      file: core.yml
      service: redis

  elasticsearch:
    extends:
      file: core.yml
      service: elasticsearch

  logstash:
    restart: always
    build: ../logstash
    depends_on:
      - postgres
      - elasticsearch
    links:
      - postgres:database
      - elasticsearch:elasticsearch
