version: '2'
services:
  postgres:
    restart: always
    build: ../postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    restart: always
    build: ../logstash
    depends_on:
      - postgres
      - elasticsearch
    links:
      - postgres:database
      - elasticsearch:elasticsearch
