version: '2'
services:
  postgres:
    restart: always
    build: ../postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb

  postgres_test:
    restart: always
    build: ../postgres
    ports:
      - "5555:5432"
    volumes:
      - /var/lib/postgresql
