version: '2'
services:
  frontend:
    restart: always
    build: ../frontend
    ports:
      - "3000:3000"
    command: npm start

  postgres:
    extends:
      file: core.yml
      service: postgres

  redis:
    extends:
      file: core.yml
      service: redis
