version: '2'
services:
  frontend:
    restart: always
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/frontend
    command: npm run rebuildstart

  mongodb:
    extends:
      file: core.yml
      service: mongodb

  postgres:
    extends:
      file: core.yml
      service: postgres

  redis:
    extends:
      file: core.yml
      service: redis
