version: '2'
services:
  frontend:
    extends:
      file: frontend.yml
      service: frontend
    volumes:
      - /frontend/dist
    command: bash -c "node --max-old-space-size=512 ./node_modules/webpack/bin/webpack.js --config config/webpack.prod.js --progress --profile --bail && tail -f /dev/null"

  postgres:
    extends:
      file: core.yml
      service: postgres

  redis:
    extends:
      file: core.yml
      service: redis

  backend:
    restart: always
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    volumes:
      - ../backend:/backend
    links:
      - postgres:database
      - redis:cache
      - elasticsearch:elasticsearch
    command: /go/bin/backend

  elasticsearch:
    extends:
      file: core.yml
      service: elasitcsearch

  logstash:
    restart: always
    build: ../logstash
    depends_on:
      - postgres
      - elasticsearch
    links:
      - postgres:database
      - elasticsearch:elasticsearch

  nginx:
    restart: always
    build: ../nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes_from:
      - frontend
    links:
      - frontend
      - backend
