version: '2'
services:
  postgres_test:
    restart: always
    build: ../postgres
    ports:
      - "5433:5432"

  redis_test:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"
