version: '2'
services:
  postgres_test:
    restart: always
    build: ../postgres
    ports:
      - "5432:5432"

  redis_test:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
